### ISSUE TITLE
Scanning code crashes if DiceKey in partial view

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/beta-program#3]
```
01030176:0x6e0eb Uncaught RuntimeError: memory access out of bounds
    at writeFaceCharacters(cv::Mat&, cv::Point_<float>, float, float, char, char, Color, Color) (<anonymous>:wasm-function[2558]:0x6e0eb)
    at visualizeReadResults(cv::Mat&, std::__2::vector<FaceRead, std::__2::allocator<FaceRead> > const&, float, float) (<anonymous>:wasm-function[2526]:0x6cb61)
    at DiceKeyImageProcessor::augmentRGBAImage(int, int, unsigned int*) (<anonymous>:wasm-function[2015]:0x5a178)
    at processAndAugmentRGBAImage(DiceKeyImageProcessor&, int, int, emscripten::val const&) (<anonymous>:wasm-function[66]:0x3834)
    at emscripten::internal::FunctionInvoker<bool (*)(DiceKeyImageProcessor&, int, int, emscripten::val const&), bool, DiceKeyImageProcessor&, int, int, emscripten::val const&>::invoke(bool (**)(DiceKeyImageProcessor&, int, int, emscripten::val const&), DiceKeyImageProcessor*, int, int, emscripten::internal::_EM_VAL*) (<anonymous>:wasm-function[64]:0x375a)
    at dynCall_iiiiii (<anonymous>:wasm-function[6119]:0x18b59b)
    at Module.dynCall_iiiiii (https://dicekeys.app/dicekey-image-frame-worker.ad1982c6.js:51418:42)
    at dynCall_iiiiii_6 (eval at makeDynCaller (https://dicekeys.app/dicekey-image-frame-worker.ad1982c6.js:49459:19), <anonymous>:4:12)
    at DiceKeyImageProcessor$processAndAugmentRGBAImage [as processAndAugmentRGBAImage] (eval at new_ (https://dicekeys.app/dicekey-image-frame-worker.ad1982c6.js:49694:27), <anonymous>:11:10)
    at FrameProcessingWorker.processRGBAImageFrameAndRenderOverlay (https://dicekeys.app/dicekey-image-frame-worker.ad1982c6.js:53779:31)
```

![image](https://user-images.githubusercontent.com/8259431/93563397-c27a7b80-f9c2-11ea-952f-8fff79e12083.png)

This may be a repro of issue #2.

**Comment by UppaJung** [comment]
Fixed here, then propagated up.
https://github.com/dicekeys/read-dicekey/commit/334e8c3238accd0aed559aae4820caed3a6ec420
